#version: "3.9"
services:
  postgres:
    image: debezium/postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
#      - ./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    #    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=employee_manage
    networks:
      - lexuancong-network

  pgadmin:
    image: dpage/pgadmin4:2024-10-19-2
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: xuancong@admin.com
      PGADMIN_DEFAULT_PASSWORD: xuancong
    networks:
      - lexuancong-network

networks:
  #  các service có cùng mạng thì cos thể kết nối với nhau
  lexuancong-network:
    driver: bridge
    name: lexuancong-network

volumes:
  postgres:
  pgadmin:
  redis:





